// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjJeO4h2n4XISQV4dfd6X2q8ELPV-W0YU',
    appId: '1:665451860631:web:81c703f3551188441e4fd2',
    messagingSenderId: '665451860631',
    projectId: 'shoppinglist-3ee28',
    authDomain: 'shoppinglist-3ee28.firebaseapp.com',
    databaseURL: 'https://shoppinglist-3ee28-default-rtdb.firebaseio.com',
    storageBucket: 'shoppinglist-3ee28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3wIgM1xxLsFNBd39W61rV6wnXI618zqE',
    appId: '1:665451860631:android:c449ca57c0f62bd21e4fd2',
    messagingSenderId: '665451860631',
    projectId: 'shoppinglist-3ee28',
    databaseURL: 'https://shoppinglist-3ee28-default-rtdb.firebaseio.com',
    storageBucket: 'shoppinglist-3ee28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJKFNmhlL8Ov9A4oxXe0LsPqA9N6dQ_Y',
    appId: '1:665451860631:ios:ef8a96cd15b7a6011e4fd2',
    messagingSenderId: '665451860631',
    projectId: 'shoppinglist-3ee28',
    databaseURL: 'https://shoppinglist-3ee28-default-rtdb.firebaseio.com',
    storageBucket: 'shoppinglist-3ee28.appspot.com',
    iosClientId: '665451860631-sdg26hbp6a3atubcntf9t4rrs9htvuap.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppinglist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJKFNmhlL8Ov9A4oxXe0LsPqA9N6dQ_Y',
    appId: '1:665451860631:ios:ef8a96cd15b7a6011e4fd2',
    messagingSenderId: '665451860631',
    projectId: 'shoppinglist-3ee28',
    databaseURL: 'https://shoppinglist-3ee28-default-rtdb.firebaseio.com',
    storageBucket: 'shoppinglist-3ee28.appspot.com',
    iosClientId: '665451860631-sdg26hbp6a3atubcntf9t4rrs9htvuap.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppinglist',
  );
}
